services:
  db:
    build: ./db-service
    image: seznam/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SEZNAM_DB_PASSWORD=${SEZNAM_DB_PASSWORD}
    ports:
    - 5432:5432
  django:
    build: ./backend-service
    image: seznam/backend
    volumes:
      - ./backend-service:/seznam/
    environment:
      - SEZNAM_DB_PASSWORD=${SEZNAM_DB_PASSWORD}
    command: poetry run python ./seznam/seznam_django/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:7
  celery:
    build: ./backend-service
    volumes:
      - ./backend-service:/seznam/
    command: poetry run celery --workdir ./seznam/seznam_django -A seznam_django worker -l info
    depends_on:
      - redis
    environment:
      - SEZNAM_DB_PASSWORD=${SEZNAM_DB_PASSWORD}
  celery-beat:
    build: ./backend-service
    volumes:
      - ./backend-service:/seznam/
    command: poetry run celery --workdir ./seznam/seznam_django -A seznam_django beat -l info
    depends_on:
      - redis
