# Generated by Django 4.1.7 on 2023-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_fetchmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('short_name', models.CharField(max_length=2048)),
                ('icon_uri', models.CharField(max_length=2048)),
                ('manifest_uri', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('is_featured', models.BooleanField()),
                ('complete_json', models.JSONField()),
                ('drms', models.ManyToManyField(to='videos.drm')),
                ('features', models.ManyToManyField(to='videos.feature')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
